services:
  - type: web
    name: mcp-train-flight-server
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: API_BEARER_TOKEN
        value: your_bearer_token_here
      - key: RAPIDAPI_KEY
        value: your_rapidapi_key_here
